name: go-api-products

services:
  api:
    build:
      context: .
    profiles:
      - with_api
    cpus: 1
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: go-api-products
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-api-products
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: {}