name: go-api-products

services:
  api:
    build:
      context: .
    profiles:
      - with_api
    cpus: 1
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: go-api-products
      USE_CACHE: true
      REDIS_HOST: redis:6379
      REDIS_PASSWORD: 
      REDIS_DATABASE: 0
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-api-products
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: {}